### ISSUE TITLE
VS 2017 and VS 2019 support?

### ISSUE THREAD

**Issue by BlinksTale** [davidjohnoliver/CodeConnections#12]
This is a great looking tool and I'm looking forward to using it, but I'm curious how hard it would be to put on an older version of Visual Studio. I'd love to not ask my teammates to upgrade their IDE just for one extension, but I don't know how easy it is to backport this stuff. 

No problem if that's a nontrivial task, just worth asking. Thank you!

**Comment by davidjohnoliver** [comment]
Thanks for your interest and kind words!

As far as support for older VS versions:

 - **VS 2019:** in fact the extension already works, it's just not listed since it's unfortunately [not possible to have multiple VS versions in the same Visual Studio Marketplace listing](https://developercommunity.visualstudio.com/t/Single-VSIX-entry-in-Visual-Studio-marke/1584630#T-ND10242417). VS 2019 users who want to install Code Connections can grab the VSIX directly from the build artifacts from a recent CI run under the 'Actions' tab, eg: https://github.com/davidjohnoliver/CodeConnections/actions/runs/3923070538 . I'll try to make a GitHub release for the next stable version, so that the binary doesn't expire.
 - **VS 2017:** this would be a bigger lift - it would entail downgrading the SDK versions (Roslyn, etc) used by the tool, and perhaps other adjustments. It's not something I'm planning to tackle, but I'd be happy to take an external contribution. :) The actual code is already in a shared project, at least.

**Comment by BlinksTale** [comment]
Even just 2019 is great, thank you! Looking forward to that in the next release. Feel free to resolve this issue now, or once that 2019 version is in the Release section - both feel resolved to me.
